on:
  pull_request:
    types: ["opened", "reopened"]
    
permissions:
  issues: write
  pull-requests: write
  contents: write
  checks: read
  statuses: read
    
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps: 
        - name: Add "automerge" tag
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const prNumber = context.payload.pull_request.number;
                const prName = context.payload.pull_request.title;
                
                if (prName.substring(0, 5) === 'chore') {
                    github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: prNumber,
                        labels: ['automerge']
                    });
                } else {
                    console.log('The found pull request did not contain "chore" in its title.');
                }
  
  automerge-version-pull-request:
    runs-on: ubuntu-latest
    needs: add-label
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
